### ISSUE TITLE
support MQTT-SN

### ISSUE THREAD

**Issue by gedw99** [emitter-io/emitter#180]
MQTT-SN uses UDP.
Its normally used for sensor data and it would be most useful to me.

I found a few implementations, and have not tried them yet.
https://github.com/Kmotiko/ceratopoGon

Please let me know if your open to eventually adding this to your roadmap.

**Comment by Kelindar** [comment]
Thanks @gedw99 for suggesting MQTT-SN, I had a look and it wouln't fit very nicely with emitter directly as from what I gather MQTT-SN is supposed to be used as a gateway and have MQTT broker behind. Seems like more appropriate usage of MQTT-SN would be in a some sort of a gateway appliance (eg: Alexa-like)

I do see the use for sensor networks and UDP, but we still need to find a way to properly secure this. Currently in the MQTT-SN specification you'd need to pre-register topics and then provide topic IDs which sounds almost impossible to secure in an unsecure network. 

Maybe instead of doing that, supporting full MQTT publish over UDP would be more useful? Given that emitter doens't actually require authentication and has channel keys, we could have a separate UDP listener on the same port which only listens for publish operations - this would allow sensor networks to publish messages to emitter without any connection drama.

**Comment by Kelindar** [comment]
@gedw99 I'm thinking about implementing an "emitter-gateway" sometime in future. Here's something which maybe able to alleviate some of the sensor network headaches (still TCP though): https://github.com/emitter-io/emitter/pull/183
