### ISSUE TITLE
How do channel keys still work after a restart?

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#196]
Hi,
Thanks for sharing this great pub/sub server.

While playing with client SDK, I saw that a channel key is persisted somehow after the server is restarted. (I can use the same key after a server restart)

My configuration is as follows:

```
{
	"listen": ":8080",
	"license": "z1Rn5FD_Bae0A_elLSv1RPYn2Is6XBY9AAAAAAAAAAI",
	"tls": {
		"listen": ":443",
		"certificate": "cert.pem",
		"private": "key.pem"
	},
	"cluster": {
		"listen": ":4000",
		"advertise": "external:4000"
	},
	"storage": {
		"provider": "inmemory"
	}
}
```
Since the storage was configured to be in memory, how does this work?

**Comment by Kelindar** [comment]
Emitter doesn't persist any channel keys. This works, because the `license` contains an encryption key and this license is used to symmetrically encrypt the channel keys when they are created and decrypt them when they are received. So if you restart the server with the same license, all of the keys will work. 

This package has more info: https://github.com/emitter-io/emitter/tree/master/internal/security

**Comment by postacik** [comment]
Does this mean every key contains information about its channel and its rights?

**Comment by Kelindar** [comment]
Yes, they contain the info about the target channel & sub-channels (with wildcards), permissions, TTL and some randomness.

**Comment by postacik** [comment]
Very well, thanks :)))
