### ISSUE TITLE
Generating keys without the API

### ISSUE THREAD

**Issue by Sexual** [emitter-io/emitter#232]
I'm looking to try to implement key generation without using the API/WS due to firewall limits and basic performance improvements.

Are there any outlines to the keygen process (other than reading the code itself)?

**Comment by kelindar** [comment]
Not sure what you mean, are you trying to generate keys without the broker?

**Comment by Sexual** [comment]
@kelindar Yes, that is correct.

**Comment by kelindar** [comment]
Have a look here: https://github.com/emitter-io/emitter/blob/master/internal/security/crypto_test.go#L177-L212

You'd need to use `security` package, which would require a license key in order to generate the key.  This package doesn't depend on the broker and is fairly simple. Only slight problem is that it's in `internal` and you won't be able to import it.

**Comment by Sexual** [comment]
My issue is that the project I would integrate it with isn't using Go.

**Comment by kelindar** [comment]
Which language you'd require?

**Comment by Sexual** [comment]
Ruby

**Comment by kelindar** [comment]
The way I see it, you have a few options, but they're not looking very good:

1. Reimplement the security package in Ruby. Sadly, we don't have any documentation on this so you'd need to read the code in this package and translate it to Ruby.
2. You could create a smaller sidecar HTTP server in Go which exposes this functionality to your Ruby application.
3. You could bundle the `security` package along with a main file and build a shared library (.so) and then call that from Ruby as [described here](https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf).
