### ISSUE TITLE
Two questions about the inner workings of emitter

### ISSUE THREAD

**Issue by postacik** [emitter-io/emitter#235]
Question 1:
When I subscribe the presence of a channel, I get an unsubscribe event when a user subscribed to that channel disconnects.

Does this mean the emitter engine clears all subscriptions of a client when the client disconnects?

If the client re-connects using the same id, will he still receive messages for the pre-subscribed channels?

Question 2:

Suppose we have a cluster of 2 emitter nodes.

First, node1 is started and clients start connecting and subscribing to channels.

When node2 is started after some time, is it synchronized with node1 so that it gets the equal inner state of node1?

Thanks :)

**Comment by Florimond** [comment]
1) There is no concept of "session". When you reconnect, you'll have to resubscribe. That's why subscriptions should be done in the connect handler, so the client automatically resubscribe upon re-connection.

2) When you join a new node to the cluster, eventually all nodes will be aware of this new node, and eventually the the subscription list will be the same all nodes. But stored messages are not replicated. That's why, if you want to store important message for a long time, you should use the ssd store in a kubernetes volume. If you use the in-memory store, you'll loose the messages in case of failure of the host.

**Comment by postacik** [comment]
Thanks.

To clarify your answer to question 2:

To access TTL > 0 messages, all clusters must use the same ssd store. Is that true?

**Comment by Florimond** [comment]
Not to loose any stored messages, every broker should have a ssd store. And for performance purposes they should have their own ssd store. Stored messages are queried on every broker and aggregated before being returned. So you will receive messages stored by all brokers, even though they don't share the store.

**Comment by postacik** [comment]
That's great news. Thanks 👍
