### ISSUE TITLE
Software Licensing Question

### ISSUE THREAD

**Issue by JohnRoesler** [emitter-io/emitter#258]
I understand there are likely thought out reasons and motivations for Emitter choosing the AGPL. I realize this is a long shot, but have you considered relicensing it under a permissive license such as MIT, Apache, or even just GPL?

**Comment by StephanSchuster** [comment]
I am also very interested in this topic as AGPL is a real problem in our case.

**Comment by Florimond** [comment]
Hello @JohnRoesler and @StephanSchuster,

what exactly do you want to do that is not allowed by AGPL? I can't remember exactly the discussions we had when choosing this licence, but I can pass the message and maybe discuss it again with the team...

**Comment by rum-runner** [comment]
I have worked for several companies that do not allow AGPL. Here is an example that is often shared when I have asked them why:

> Say you're building a service that is made up of many micro services - it is unclear from the AGPL license and legal precedents whether or not you could be forced to make public your entire codebase for a project if an AGPL product is used as a component. In this case - if you were building a service that used emitter to pass messages between micro services you would not want to be forced to share back all the elements not directly related to the emitter codebase.

Basically, they view it as not a risk worth taking. I would love to contribute back to emitter and could see using it at my current company if a different license was selected so that the legal folks would allow us to use it.

Not sure if others face the same - but that is my perspective.

**Comment by StephanSchuster** [comment]
What @rum-runner described is exactly the same issue I face in my company. That's a pity because otherwise emitter seems to be a perfect fit.

Another issue I'm facing is with all the Eclipse PAHO based emitter client SDKs: PAHO is based on EPL1.0 and EDL 1.0 which AFAIK suffers from the same limitations as AGPL that @rum-runner described ("make public your entire codebase"). Correct me if I'm wrong.

**Comment by JohnRoesler** [comment]
I see that as the main issue also. An article I was reading the other day says it well IMO - from [tech republic](https://www.techrepublic.com/blog/10-things/dont-believe-the-hype-agpl-open-source-licensing-is-toxic-and-unpopular/)

> The collateral damage in this bargain, however, is developers. Developers want to get stuff done with a minimum of overhead (be it infrastructure or lawyers). In fact, this shift toward permissive licensing has become so pronounced that on GitHub it's still far too common for projects not to have a license at all.

**Comment by Florimond** [comment]
After briefly discussing this with our guru, it seems like AGPL shouldn't be a problem. Like it's not a problem for all the people using projects like MongoDB: https://www.mongodb.com/blog/post/the-agpl

> Note however that it is NOT required that applications using mongo be published.  The copyleft applies only to the mongod and mongos database programs.  This is why Mongo DB drivers are all licensed under an Apache license.  You application, even though it talks to the database, is a separate program and “work”.
