### ISSUE TITLE
Expose internal package for user custom usage

### ISSUE THREAD

**Issue by leaxoy** [emitter-io/emitter#287]
This is a great project, but in some case, I want use this package for some customize, and should register user handler for flexible.
Thanks for your work

**Comment by shushenghong** [comment]
+1

**Comment by kelindar** [comment]
I'm not very keen on exposing all of the internal packages as we make breaking changes and if people take dependency on them, it would require us to maintain a stable API. 

This being said we could expose the broker alone for embedding purposes. What's the ultimate goal here?

**Comment by shushenghong** [comment]
Thank you @kelindar, I understand your concerns.
As myself, I want to use emitter as a go module in my project, a little bit of function expansion, maybe expand the conn/events related to the project, so even emitter break changes will be fine since I know this situation, emitter is very fully functional 
 now, i only need a little bit of expansion for special project usage.
