### ISSUE TITLE
Can emitter avoid gossip the full state periodically?

### ISSUE THREAD

**Issue by DrmagicE** [emitter-io/emitter#358]
Hi, thank for building this great project.

I am curious about how emitter sync the state(subscription,connection.. etc) in cluster.
After doing some digging, I found it is using gossip and delta-CRDT, and it seams emitter will also perform full sync periodically. (30 seconds).

Just wondering can we avoid the full sync because the full sync size can be large and may hurt performance.
If delta-CRDT has already provided eventual consistency, then performing a full sync seems to be unnecessary.

**Comment by kelindar** [comment]
Hi @DrmagicE, it's true that we're doing delta syncs with every update and gossip full-state sync every 30 seconds. I'm impressed you've noticed this. 

It is indeed not necessary to do a full sync, however at least partial sync of old info is required, since nodes can come up later in time, so they will need to get "eventually sync'd", with the current approach the "eventually" is  equals to ~30 seconds. This can be replaced with a gossip of a periodic random sample (say 1MB of data every 10 seconds), which would eventually converge as well and limit the number of network traffic between the nodes. Future improvements to consider.
