### ISSUE TITLE
The provider 'ssd' could not be loaded. manifest has unsupported version: 4 (we support 8).

### ISSUE THREAD

**Issue by gtmadev** [emitter-io/emitter#373]
I just pulled the latest and now my container fails to start. Something about 'ssd' not being a valid provider. But I just looked at the docs, and it is a valid provider. What changed? I need to get this back online.

`2021/06/28 10:12:01 [service] configured logging provider (stderr),
panic: The provider 'ssd' could not be loaded. manifest has unsupported version: 4 (we support 8).,
Please see https://github.com/dgraph-io/badger/blob/master/README.md#i-see-manifest-has-unsupported-version-x-we-support-y-error on how to fix this. [recovered],`

I tried to look at the "how to fix this", but it does not go anywhere. There's no anchor like that on the page being linked to.

FYI.. I also see an issue just below this one about Badger 3 now being used for storage, including the 'ssd' provider. So, do I need to change something with my provider designation in my environment variables?

**Comment by kelindar** [comment]
Yeah I haven't done the release yet, will do 2 releases just for this. Basically `badger/v3` is not binary compatible with `badger/v1` which is relatively old now and unsupported. 

The easiest solution to your problem is to delete old data and let it create a new volume. Alternatively, you would need to run 2 clusters (old and new) and let the old data expire slowly while directing traffic to only new brokers.

**Comment by gtmadev** [comment]
Yeah, I was just looking at the data folder in my persisted container volume. I see there's a manifest file there and some logs. I will just let it recreate. There's nothing critical that can be lost. The ssd storage is just very short-term.

**Comment by gtmadev** [comment]
All set. That worked as expected. Everything is good to go. Thanks for the quick assistance. :)
